source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/skylib/SnapPods.git'

platform :ios, '8.0'

target 'SnapOnboarding-iOSExample' do
  use_frameworks!

  pod 'HanekeSwift', :git => "https://github.com/chadmoone/HanekeSwift.git", :branch => "feature/swift-2.3"
  pod 'SnapOnboarding-iOS', :path => '../'

end
