source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/skylib/SnapPods.git'

platform :ios, '9.0'

target 'SnapOnboarding-iOSExample' do
  use_frameworks!

  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift', :branch => 'feature/swift-3'
  pod 'SnapOnboarding-iOS', :path => '../'

end
