source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/skylib/SnapPods.git'

platform :ios, '8.0'

target 'SnapOnboarding-iOS' do
  use_frameworks!

  pod 'SnapFonts-iOS'
  pod 'SnapTagsView'
  pod 'TTTAttributedLabel'

  target 'Snapshot_tests' do
    inherit! :search_paths

    pod 'SnapFBSnapshotBase'
  end

  target 'Unit_tests' do
    inherit! :search_paths
  end

end
