source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/skylib/SnapPods.git'

platform :ios, '9.0'

target 'SnapOnboarding-iOS' do
  use_frameworks!

  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift', :branch => 'feature/swift-3'
  pod 'SnapFonts-iOS'
  pod 'SnapTagsView'
  pod 'TTTAttributedLabel'

  target 'Snapshot_tests' do
    inherit! :search_paths

    pod 'SnapFBSnapshotBase'
  end

  target 'Unit_tests' do
    inherit! :search_paths
  end

end
